language: node_js
cache: yarn
os:
  - linux
  - osx
  - windows
node_js:
  - "8"
  - "6"
before_script:
  - bash
  - yarn flow
# Tests are run on the prepublish hook which fires after install
# No need to run tests twice.
script: echo "noop"
