language: node_js
cache: yarn
os:
  - linux
  - osx
  - windows
node_js:
  - "8"
  - "10"
# before_script: yarn build
# Tests are run on the prepublish hook which fires after install
# No need to run tests twice.
script: echo "noop"
